### PR TITLE
last change went wrong because of hard remove, this is working well now, passed storybook and coverage tests

### PR DESCRIPTION
**Pull request by AnvithaKosuri**

### CODE REVIEW

**Comment by st4lemon** [comment]
add storybook link and screenshot of the form as outlined in the issue

**Comment by AnvithaKosuri** [comment]
Screenshot 2024-11-07 at 5 34 25 PM

**Comment by AnvithaKosuri** [comment]
https://6722c2d8d8e479c1c618f650-wzolheqxhd.chromatic.com/?path=/docs/components-helprequest-helprequestform--docs

**Comment by clevermonkey16** [comment]
Closed: we redoing this one

**Pull request closed without merging**
